//graphQL 명령어 test

query {
	getAccountInfo{
    id
    nickname
    image
	}
}


// 이모티콘 전체
query {
	getAllEmoticons{
    fileUrl
    name
	}
}

// 물어봐
query {
	getQuestionPosts(userId : 1){
    id
		content
    postType
    usingEmoticons{
      id
      positionX
      rotate
    }
    Emoticons{
      fileUrl
      name
    }
	}
}

// 답해줘
query {
	getAnswerPosts(userId : 1){
    id
		content
    postType
    usingEmoticons{
      id
      positionX
      rotate
    }
    Emoticons{
      fileUrl
      name
    }
	}
}


// 로그인
mutation{
  signIn(provider:"Kakao", accessToken:"V4ySwaJXNWtQyqbt8NGwPWz2r1sbo83GHx022QorDKYAAAF54JdzUg"){
    token
  }
}

// post 생성
mutation{
  createPost(
    content: "aaa",
    color: "#777",
    secretType: "Temp",  
    postType: "Answer",
		toAccountId: "1",
    emoticons: [
      {
        emoticonId: "1"
      }
    ]
  ){
    content
    postType
    color
    postState
    secretType
  }
}



// post 삭제
mutation{
  deletePost(
    postId: 1
  )
}

// post 좋아요 생성
mutation{
  createLikePosts(
    postId: 1,
  ){
		id
  }
}


// post 좋아요 삭제
mutation{
  deleteLikePosts(
    postId: 1,
  )
}

# 코멘트 생성
mutation {
  createComment(postId:"1", content:"댓글테스트", secretType:"Forever") {
    id
    content
    
  }
}

// 프로필 수정
mutation{
  updateAccountInfo(
    nickname:"ddddd", 
    providerId: "1706701468"
		content: "aaaa"
  ){
    nickname
    image
    content
    profileUrl
  }
}

// 프로필 이미지 변경
 mutation updateImage($file: Upload!) {
	updateImage(file: $file)
	}

{"query":"mutation updateImage($file: Upload!) {\n\tupdateImage(file: $file, providerId: \"1706701468\"){\n    image\n  }\n}"}

// curl: // {"query":"mutation updateImage($file: Upload!) {\n\tupdateImage(file: $file, providerId: \"1706701468\")\n}"}
postman에서 실행

[Headers]
key                    value
authorization          Bearer ~~

[Body]
key                     value
operations             {"query":" mutation updateImage($file: Upload!) {\n\tupdateImage(file: $file)\n\t}"}
map                    {"0": ["variables.file"]}
0                      파일추가

// 기본이미지로 사진 변경
mutation{
  updateImageToBasic
}

// 문의하기
mutation{
  createContact(
		content: "aaaa"
  ){
		id
    content
  }
}