//graphQL 명령어 test


//사용자 전체 목록
query {
	users{
    id
    nickname
    userId
    password
    createdAt
    updatedAt
	}
}


//사용자 1번 찾기  -> comment join은 잘 모르겠..
query {
	user(id : 1){
    id
    nickname
    userId
    password
    createdAt
    updatedAt
	}
}


//사용자 입력
mutation {
  insertUsers (
    nickname: "deeo",
    userId: "66",
    password: "4232",
  ) {
    nickname
    userId
    password
  }
}


mutation{
  signIn(provider:"Kakao", accessToken:"onrx5LiuAb6eotfyygH1WisM3ceBxBhBf2Xk2worDR4AAAF5CJInxw"){
    token
  }
}

// jwt : eyJhbGciOiJIUzI1NiJ9.MTcwNjcwMTQ2OA.lWvEo8fZUAGsynyvxTC9H3Zz1Av9Cjb2WRESDsT5TSQ

mutation{
  makePost(
    content: "aaa",
    postType: "question",
    color: "#777",
    postState: "submitted",
    secretType: "no",  
  ){
    content
    postType
    color
    postState
    secretType
  }
}


mutation{
  deletePost(
    id: 1
  ){
		id
  }
}