//graphQL 명령어 test


//사용자 전체 목록
query {
	users{
    id
    nickname
    userId
    password
    createdAt
    updatedAt
	}
}


//사용자 1번 찾기  -> comment join은 잘 모르겠..
query {
	user(id : 1){
    id
    nickname
    userId
    password
    createdAt
    updatedAt
	}
}


//사용자 입력
mutation {
  insertUsers (
    nickname: "deeo",
    userId: "66",
    password: "4232",
  ) {
    nickname
    userId
    password
  }
}


mutation{
  signIn(provider:"Kakao", accessToken:"t0weVUprlo48U8nbs0V5A8OGNlnfDMtiPkBSMgo9c5sAAAF5A_-dOg"){
    token
  }
}

mutation{
  makePost(
    content: "aaa",
    postType: QUESTION,
    color: "Red",
    state: SUBMITTED,
    secretType: "no",  
  ){
    content
    postType
    color
    state
    secretType
  }
}


mutation{
  deletePost(
    id: 1
  ){
		id
  }
}